name: "Publish to mvn central"
on:
  workflow_dispatch:
  push:
    tags:
      - '*[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup JDK"
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: "Setup Android"
        uses: android-actions/setup-android@v3
      - name: "Build and publish library"
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_PASS }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MVN_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MVN_GPG_PASS }}
        run: |
          chmod u+x ./gradlew
          ./gradlew publishAndReleaseToMavenCentral -Dorg.gradle.parallel=false --stacktrace --no-configuration-cache